const actions = {
  GET_DATA: 'GET_DATA',
  GET_DATA_TITLE: 'GET_DATA_TITLE',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_CURRENCY: 'GET_DATA_CURRENCY',
  GET_DATA_CURRENCY_SUCCESS: 'GET_DATA_CURRENCY_SUCCESS',
  GET_CHANGE_DATA: 'GET_CHANGE_DATA'
};
export default actions;

